### ISSUE TITLE
Metrics metadata

### ISSUE THREAD

**Issue by robhudson** [mozilla/distribution-viewer#92]
Currently we store metrics metadata in the `api_metrics` table. There will be more columns that are needed and the database on Heroku may not be the most accessible as it would require an account and access via the Django admin.

One suggestion was to capture this metadata in a Google spreadsheet which is nice for easy access but perhaps not so nice for querying it via request/response cycles on the website. If it doesn't change often we could export the metadata from Google spreadsheets into the Heroku database for the website and aggregation scripts.

**Comment by rafrombrc** [comment]
Stream of consciousness thoughts on this: Ultimately, I think we want to move towards a situation where all of our metadata about the data sets we have and the metrics we capture are exposed via a web service, so they can be made consistently available to all of ATMOsphere (including sql.t.m.o and dist viewer). We probably don't want to get ahead of ourselves and boil the ocean here just yet, though.

For now, since the set of folks modifying this data set will be small, keeping it in this database and providing access via the django admin UI might suffice. If possible, it'd be great to put it together in a way that supports converting down the line to a world where the metrics metadata lives outside of the distribution viewer and is retrieved via HTTP.

**Comment by robhudson** [comment]
Commit baa7f1a5d3079ccda1daf60d5ebdfa2cab420f98 adds the ability to edit the `Metric` table in the Django admin. Closing this issue for now.

**Comment by openjck** [comment]
Is the plan to also capture other metadata (like chart descriptions) in Django admin?

**Comment by robhudson** [comment]
> Is the plan to also capture other metadata (like chart descriptions) in Django admin?

Yes. We have the description field in this table currently, but we will need to add other fields for other metadata, like the tooltip on hover strings.
